name: Generate Snake

on:
  # Chạy tự động mỗi 12 tiếng
  schedule:
    - cron: "0 */12 * * *"
  
  # Cho phép bạn tự bấm chạy thủ công
  workflow_dispatch:
  
  # Chạy mỗi khi bạn push code lên nhánh main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Tạo file SVG snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Cấu hình màu sắc đồng bộ với giao diện Portfolio Dark Mode
          # color_snake: màu của con rắn (màu tím purple)
          # color_dots: 5 mã màu của các ô vuông đóng góp từ nhạt đến đậm
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=purple&color_dots=#201f1f,#0f5261,#177a90,#1bb5cd,#53ddfc

      # Step 2: Đẩy file SVG vừa được tạo lên branch có tên là "output"
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Branch này sẽ tự động sinh ra
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
